# CircleCI configuration file
version: 2.1

jobs:
  build:
    docker:
      - image: rust:1.62.1-buster
    steps:
      - checkout
      - run: |
          git tag circle-$CIRCLE_BUILD_NUM
          git push origin --tags
          apt-get update
          apt-get install -y cmake
          mkdir -p $HOME/d/protoc
          cd $HOME/d/protoc
          export PROTO_ZIP="protoc-21.4-linux-x86_64.zip"
          curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v21.4/$PROTO_ZIP
          unzip $PROTO_ZIP
          export PATH=$PATH:$HOME/d/protoc/bin
          protoc --version
          cd -
          cargo build --release --all
      - persist_to_workspace:
          root: /root
          paths:
            - project/helm
            - project/target/release/ballista-scheduler
            - project/target/release/ballista-executor
            - project/scheduler.Dockerfile
            - project/executor.Dockerfile

  deploy_docker:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /root
      - run: |
          docker build -f scheduler.Dockerfile . -t spaceandtime.jfrog.io/sxt-docker-docker/ballista-scheduler:$CIRCLE_BUILD_NUM
          docker build -f executor.Dockerfile . -t spaceandtime.jfrog.io/sxt-docker-docker/ballista-executor:$CIRCLE_BUILD_NUM
          docker login -u$ARTIFACTORY_USER -p$ARTIFACTORY_API_KEY spaceandtime.jfrog.io
          docker push spaceandtime.jfrog.io/sxt-docker-docker/ballista-scheduler:$CIRCLE_BUILD_NUM
          docker push spaceandtime.jfrog.io/sxt-docker-docker/ballista-executor:$CIRCLE_BUILD_NUM

  deploy_helm:
    docker:
      - image: mcr.microsoft.com/azure-cli
    steps:
      - attach_workspace:
          at: /root
      - run: |
          cd /root/project/helm/ballista     
          az login --username=$AZ_USER --password=$AZ_PASS
          az aks get-credentials --resource-group DATA-WAREHOUSE-TEST --name DATA-WAREHOUSE-TEST-CLUSTER --admin
          kubectl create secret docker-registry regcred --docker-server=https://spaceandtime.jfrog.io/sxt-docker-docker --docker-username=$ARTIFACTORY_USER --docker-password=$ARTIFACTORY_API_KEY --docker-email=$ARTIFACTORY_EMAIL || true
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm upgrade --install ballista . --debug --set image.scheduler=ballista-scheduler --set image.executor=ballista-executor --set image.tag=$CIRCLE_BUILD_NUM --set image.repository=spaceandtime.jfrog.io/sxt-docker-docker

workflows:
  main_workflow:
    jobs:
      - build
      - deploy_docker:
          requires:
            - build
      - deploy_helm:
          requires:
            - deploy_docker
