# CircleCI configuration file
version: 2.1

jobs:
  build:
    docker:
      - image: rust:1.62.1-buster
    steps:
      - checkout
      - run: |
          apt-get update
          apt-get install -y cmake
          mkdir -p $HOME/d/protoc
          cd $HOME/d/protoc
          export PROTO_ZIP="protoc-21.4-linux-x86_64.zip"
          curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v21.4/$PROTO_ZIP
          unzip $PROTO_ZIP
          export PATH=$PATH:$HOME/d/protoc/bin
          protoc --version
          cd -
          cargo build --release --all
          mkdir -p /root/project/artifacts
          mv /root/project/target/release/ballista-scheduler /root/project/artifacts/ballista-scheduler-${CIRCLE_SHA1:0:7}
          mv /root/project/target/release/ballista-executor /root/project/artifacts/ballista-executor-${CIRCLE_SHA1:0:7}
      - store_artifacts:
          path: /root/project/artifacts

workflows:
  maven_package:
    jobs:
      - build
