# CircleCI configuration file
version: 2.1

jobs:
  build:
    docker:
      - image: rust:1.62.1-buster
    steps:
      - checkout
      - run: |
          apt-get update
          apt-get install -y cmake
          mkdir -p $HOME/d/protoc
          cd $HOME/d/protoc
          export PROTO_ZIP="protoc-21.4-linux-x86_64.zip"
          curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v21.4/$PROTO_ZIP
          unzip $PROTO_ZIP
          export PATH=$PATH:$HOME/d/protoc/bin
          protoc --version
          cd -
          cargo build --release --all
          mkdir -p /root/project/artifacts
      - persist_to_workspace:
          root: /root
          paths:
            - project/target/release/ballista-scheduler
            - project/target/release/ballista-executor
            - project/scheduler.Dockerfile
            - project/executor.Dockerfile

  deploy:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /root
      - run: |
          docker build -f scheduler.Dockerfile . -t spaceandtime.jfrog.io/sxt-docker-docker/ballista-scheduler:$CIRCLE_BUILD_NUM
          docker build -f executor.Dockerfile . -t spaceandtime.jfrog.io/sxt-docker-docker/ballista-executor:$CIRCLE_BUILD_NUM
          docker login -u$ARTIFACTORY_USER -p$ARTIFACTORY_API_KEY spaceandtime.jfrog.io
          docker push spaceandtime.jfrog.io/sxt-docker-docker/ballista-scheduler:$CIRCLE_BUILD_NUM
          docker push spaceandtime.jfrog.io/sxt-docker-docker/ballista-executor:$CIRCLE_BUILD_NUM

workflows:
  maven_package:
    jobs:
      - build
      - deploy:
          requires:
            - build